/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IERC7683 {
  export type CrossChainOrderStruct = {
    settlementContract: AddressLike;
    swapper: AddressLike;
    nonce: BigNumberish;
    originChainId: BigNumberish;
    initiateDeadline: BigNumberish;
    fillDeadline: BigNumberish;
    orderData: BytesLike;
  };

  export type CrossChainOrderStructOutput = [
    settlementContract: string,
    swapper: string,
    nonce: bigint,
    originChainId: bigint,
    initiateDeadline: bigint,
    fillDeadline: bigint,
    orderData: string
  ] & {
    settlementContract: string;
    swapper: string;
    nonce: bigint;
    originChainId: bigint;
    initiateDeadline: bigint;
    fillDeadline: bigint;
    orderData: string;
  };

  export type InputStruct = { token: AddressLike; amount: BigNumberish };

  export type InputStructOutput = [token: string, amount: bigint] & {
    token: string;
    amount: bigint;
  };

  export type OutputStruct = {
    token: AddressLike;
    amount: BigNumberish;
    recipient: AddressLike;
    chainId: BigNumberish;
  };

  export type OutputStructOutput = [
    token: string,
    amount: bigint,
    recipient: string,
    chainId: bigint
  ] & { token: string; amount: bigint; recipient: string; chainId: bigint };

  export type ResolvedCrossChainOrderStruct = {
    settlementContract: AddressLike;
    swapper: AddressLike;
    nonce: BigNumberish;
    originChainId: BigNumberish;
    initiateDeadline: BigNumberish;
    fillDeadline: BigNumberish;
    swapperInputs: IERC7683.InputStruct[];
    swapperOutputs: IERC7683.OutputStruct[];
    fillerOutputs: IERC7683.OutputStruct[];
  };

  export type ResolvedCrossChainOrderStructOutput = [
    settlementContract: string,
    swapper: string,
    nonce: bigint,
    originChainId: bigint,
    initiateDeadline: bigint,
    fillDeadline: bigint,
    swapperInputs: IERC7683.InputStructOutput[],
    swapperOutputs: IERC7683.OutputStructOutput[],
    fillerOutputs: IERC7683.OutputStructOutput[]
  ] & {
    settlementContract: string;
    swapper: string;
    nonce: bigint;
    originChainId: bigint;
    initiateDeadline: bigint;
    fillDeadline: bigint;
    swapperInputs: IERC7683.InputStructOutput[];
    swapperOutputs: IERC7683.OutputStructOutput[];
    fillerOutputs: IERC7683.OutputStructOutput[];
  };
}

export interface IERC7683Interface extends Interface {
  getFunction(nameOrSignature: "open" | "resolve"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "open",
    values: [IERC7683.CrossChainOrderStruct, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "resolve",
    values: [IERC7683.CrossChainOrderStruct, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "open", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "resolve", data: BytesLike): Result;
}

export interface IERC7683 extends BaseContract {
  connect(runner?: ContractRunner | null): IERC7683;
  waitForDeployment(): Promise<this>;

  interface: IERC7683Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  open: TypedContractMethod<
    [
      order: IERC7683.CrossChainOrderStruct,
      signature: BytesLike,
      orderData: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  resolve: TypedContractMethod<
    [order: IERC7683.CrossChainOrderStruct, orderData: BytesLike],
    [IERC7683.ResolvedCrossChainOrderStructOutput],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "open"
  ): TypedContractMethod<
    [
      order: IERC7683.CrossChainOrderStruct,
      signature: BytesLike,
      orderData: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "resolve"
  ): TypedContractMethod<
    [order: IERC7683.CrossChainOrderStruct, orderData: BytesLike],
    [IERC7683.ResolvedCrossChainOrderStructOutput],
    "view"
  >;

  filters: {};
}
