/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IERC7683,
  IERC7683Interface,
} from "../../../src/interfaces/IERC7683";

const _abi = [
  {
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "settlementContract",
            type: "address",
          },
          {
            internalType: "address",
            name: "swapper",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "nonce",
            type: "uint256",
          },
          {
            internalType: "uint32",
            name: "originChainId",
            type: "uint32",
          },
          {
            internalType: "uint32",
            name: "initiateDeadline",
            type: "uint32",
          },
          {
            internalType: "uint32",
            name: "fillDeadline",
            type: "uint32",
          },
          {
            internalType: "bytes",
            name: "orderData",
            type: "bytes",
          },
        ],
        internalType: "struct IERC7683.CrossChainOrder",
        name: "order",
        type: "tuple",
      },
      {
        internalType: "bytes",
        name: "signature",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "orderData",
        type: "bytes",
      },
    ],
    name: "open",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "settlementContract",
            type: "address",
          },
          {
            internalType: "address",
            name: "swapper",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "nonce",
            type: "uint256",
          },
          {
            internalType: "uint32",
            name: "originChainId",
            type: "uint32",
          },
          {
            internalType: "uint32",
            name: "initiateDeadline",
            type: "uint32",
          },
          {
            internalType: "uint32",
            name: "fillDeadline",
            type: "uint32",
          },
          {
            internalType: "bytes",
            name: "orderData",
            type: "bytes",
          },
        ],
        internalType: "struct IERC7683.CrossChainOrder",
        name: "order",
        type: "tuple",
      },
      {
        internalType: "bytes",
        name: "orderData",
        type: "bytes",
      },
    ],
    name: "resolve",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "settlementContract",
            type: "address",
          },
          {
            internalType: "address",
            name: "swapper",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "nonce",
            type: "uint256",
          },
          {
            internalType: "uint32",
            name: "originChainId",
            type: "uint32",
          },
          {
            internalType: "uint32",
            name: "initiateDeadline",
            type: "uint32",
          },
          {
            internalType: "uint32",
            name: "fillDeadline",
            type: "uint32",
          },
          {
            components: [
              {
                internalType: "address",
                name: "token",
                type: "address",
              },
              {
                internalType: "uint256",
                name: "amount",
                type: "uint256",
              },
            ],
            internalType: "struct IERC7683.Input[]",
            name: "swapperInputs",
            type: "tuple[]",
          },
          {
            components: [
              {
                internalType: "address",
                name: "token",
                type: "address",
              },
              {
                internalType: "uint256",
                name: "amount",
                type: "uint256",
              },
              {
                internalType: "address",
                name: "recipient",
                type: "address",
              },
              {
                internalType: "uint32",
                name: "chainId",
                type: "uint32",
              },
            ],
            internalType: "struct IERC7683.Output[]",
            name: "swapperOutputs",
            type: "tuple[]",
          },
          {
            components: [
              {
                internalType: "address",
                name: "token",
                type: "address",
              },
              {
                internalType: "uint256",
                name: "amount",
                type: "uint256",
              },
              {
                internalType: "address",
                name: "recipient",
                type: "address",
              },
              {
                internalType: "uint32",
                name: "chainId",
                type: "uint32",
              },
            ],
            internalType: "struct IERC7683.Output[]",
            name: "fillerOutputs",
            type: "tuple[]",
          },
        ],
        internalType: "struct IERC7683.ResolvedCrossChainOrder",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

export class IERC7683__factory {
  static readonly abi = _abi;
  static createInterface(): IERC7683Interface {
    return new Interface(_abi) as IERC7683Interface;
  }
  static connect(address: string, runner?: ContractRunner | null): IERC7683 {
    return new Contract(address, _abi, runner) as unknown as IERC7683;
  }
}
